### ISSUE TITLE
Add mvgam to Model-based multivariate analysis section

### ISSUE THREAD

**Issue by nicholasjclark** [cran-task-views/Environmetrics#18]
The `{mvgam}` package can now fit flexible latent variable models (including JSDMs) using the new [`jsdgam()` function](https://nicholasjclark.github.io/mvgam/reference/jsdgam.html). Would it be possible to add this to the *Model-based multivariate analysis section* section using something like the following:

[mvgam](https://cran.r-project.org/web/packages/mvgam/index.html) fits Bayesian State-Space Generalized Additive Models for many data types including counts, binary observations, proportions, non-negative real values and unbounded real values. By leveraging functionalities from [brms](https://cran.r-project.org/web/packages/brms/index.html), [mgcv](https://cran.r-project.org/web/packages/mgcv/index.html) and [splines2](https://cran.r-project.org/web/packages/splines2/index.html) packages, mvgam models can include diverse predictor effects including penalized splines, Gaussian Processes, random interecepts / slopes and monotonic functions. Combined with support for a variety of temporal and spatial autocorrelation structures, this flexibility allows mvgam to fit a wide range of hierarchical ecological models including N-mixture models, Latent Variable-based Joint Species Distribution Models, and multivariate time series models with imperfect detection. The package uses [Stan](https://mc-stan.org/) for efficient Hamiltonian Monte Carlo inference.

**Comment by gavinsimpson** [comment]
Hi @nicholasjclark; would you mind prepping a PR to add something like your example paragraph? It doesn't need to be as detailed as what you have above, perhaps:

> [mvgam](https://cran.r-project.org/web/packages/mvgam/index.html) fits Bayesian State-Space Generalized Additive Models for many data types including counts, binary observations, proportions, non-negative real values and unbounded real values. mvgam can fit a wide range of hierarchical ecological models including N-mixture models, Latent Variable-based Joint Species Distribution Models, and multivariate time series models with imperfect detection.

?

**Comment by gavinsimpson** [comment]
Closed via 7a18e0d82caa8fe15bdc0cc393d2e5e13cefbd14
